extern crate rosalind;

use rosalind::dna::*;
use std::path::Path;

#[test]
fn test_from_file() {
    let scaffold = Path::new("tests/scaffolds/rosalind_dna_example");
    let dna = DNA::from_file(scaffold).ok().unwrap();
    assert!(dna != DNA::empty());
    let expected = DNA::from_str("GTCAATAACTATCAGCGAAAGGATACGTTATCGCTCACACAACACGCGCAGGCCTATCCCTTCGTCTGGACGACCTATTTAGCAAGTCCGAACCACAGCCTATATGACAATTCCCTATAGCATCTTAGTGACAGCCAAAATCAGTGATACCGAAGGCACTATATACGCGGCATGGTACTACAAACACCTCTGGTATGGGCTTGCTTTGGTATCGTTTCTTAATGGTACTGTGTCCGCCTTAGGTACTGCTGAGACAGAGCATGTATTTGGTAGGGGAGAGAGCTGATTTCTGAACCTACCCCCGTGTGAGCTCTAGATTTATGGGGGTTGTTCGTCGGCATACATAGGGATTTGGTAACTCTGGTTCCCAAAGGGCAAGGCCTCCCGGATTGCTTGATGAGAGTATAATTGTTGTGGCCGCCTTGTGGAATGCTAGGAACGTCACTTTACCCCCCCACAATAGCTATCCCATGCAGAGTCTAATTGCGAAGGAGGCATGAAGCGGGACAAGAAATTCGATCTTAAAACCGCCGCCACACAAAGTCCTTAAGGGAGGTTGACGCCAGTAAAGTCTGTACCCATCACCCCTATAGACTAAGCCCTGTATTCCAAAACCAGTTGACGTAGCTCATGTTGATGAGCGCATGTTTACATGACCCGGACACGTGAAAGCGTCCGCCACACCAGAACGCTGGCACTTGCTAACTGCAGCCGTCCTCGGGAGCGCGACCCGTTGCCCGGGCAGGGTCGAATGTTTGTAAAATTTCGTTAGTCCCGTGGTCTGACGCAATCTCATCTTTACCTGGCCTGAGTACGATGATTGTACAGATTGCTTAACAACGGATACACAAA").ok().unwrap();
    assert_eq!(dna, expected);
}
